name: Good morning

on:
  workflow_dispatch:      # ← ОБЯЗАТЕЛЬНО двоеточие
  schedule:
    - cron: '0 7 * * *'   # 10 :00 МСК = 07 :00 UTC

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install requests
      - run: python blondie_bot.py        # без аргумента → утро
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
