name: Good morning

on:
  schedule:
    # 07:00 UTC  = 10:00 по Москве (UTC+3)
    - cron:  '0 7 * * *'

jobs:
  send:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install requests
      - run: python blondie_bot.py          # утренние фразы
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
